spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/girl
    username: root
    password: prince
  jpa:
    hibernate:
      ddl-auto: update
      #自动创建！新！表（先会drop下） 根据@Entity标注的类
      #ddl-auto: create
    #控制台打印 sql语句
    show-sql: true



